### ISSUE TITLE
Rotation(like below) and magnification of the image

### ISSUE THREAD

**Issue by MetaMmodern** [paulkr/blowup.js#13]
Ok, here are two and more problems. As it was said in prev issue the magnifying lens dosn't show the rotated image, if it is rotated. Moreover, what i've found out is that if we change the width and height of an image using css, the scale attribute will be counted according to original sizes. If we change some parameters of the image(like hue or tilt), the script won't work propperly, cause it's not taking into account any changes in styles. I'll try to fix scale in a PR, but first need to understand what the scale of '1' means.

**Comment by paulkr** [comment]
These issues can be fixed now with #16.
