### ISSUE TITLE
blowup.js not following when changing src on preview element

### ISSUE THREAD

**Issue by ghost** [paulkr/blowup.js#2]
Im letting the user to choose color on a product and when clicked then main image that has blowup.js included dose not follow and displays the first image.

`
        $(".demo-img").blowup({background : "#ffffff"});

```
    jQuery('.product-preview-content').click(function(){
      var img_selected = $(this).children('img').attr('src');
      $(".product-preview").children('img').attr("src",img_selected);
    });
```

`

**Comment by paulkr** [comment]
Hello @nexxoz ! I'm not sure I fully understand what's going on. Could you explain it with a little more detail or more code snippets so I can see what's going on?

**Comment by paulkr** [comment]
Closing as there is a lack of information about this issue.
