### ISSUE TITLE
Wrong calculation because of offsetTop&Left

### ISSUE THREAD

**Issue by dmitdefn** [paulkr/blowup.js#3]
Hi,

The current version contains the code

      // Relative coordinates of image
      var relX = e.pageX - this.offsetLeft;
      var relY = e.pageY - this.offsetTop;

which does not work when the image is inside any offsetParent that itself has an offset relative to the document's top-left corner. So, while this works in demo, it doesn't in many practical cases. The following works though:

      // Relative coordinates of image
      var relX = e.pageX - $(this).offset().left;
      var relY = e.pageY - $(this).offset().top;

Good day
D

**Comment by paulkr** [comment]
Fixed, thanks!
