### ISSUE TITLE
Zoom Level

### ISSUE THREAD

**Issue by ydenizyamac** [paulkr/blowup.js#4]
Hi , im using your plugin for image zoom but i cant set level of zoom, i want less zoom value for lens.
How can i do that? 

Thanks in advance.

**Comment by paulkr** [comment]
Hey,

Thanks for reaching out! This feature has not yet been implemented. I will add this feature as soon as I find the time to get around to it. In the meantime, if you would like to open a PR, feel free!

**Comment by rok7** [comment]
Hello Paul

I had the same requirement as ydenizyamac. I'v attached my
modified blowup.js. Could you please integrate the changes?
[blowup.zip](https://github.com/paulkr/blowup.js/files/693214/blowup.zip)

Thank you

**Comment by paulkr** [comment]
@ydenizyamac, @rok7: Sorry for the delay. I have added the updated code into the repo. Good luck!

**Comment by rok7** [comment]
@paulkr: thank you very much for this great tool!
