### ISSUE TITLE
How to change background lens on thumbnail change?

### ISSUE THREAD

**Issue by unloft** [paulkr/blowup.js#6]
Hi,

I have a product page with its images (the first larger and the other thumbnails).
clicking on the thumbnails the first image changes .. ok
How can I apply the zoom to the new image?

**Comment by paulkr** [comment]
Hi @unloft,

You're able to spawn multiple different blowup lenses. Just specify the specific attributes (in your case scale) that would apply to each image that you have on your product page.

Hope this helps!
