### ISSUE TITLE
Multiple images error: zoom show always the 1st one

### ISSUE THREAD

**Issue by FGIKCM** [paulkr/blowup.js#7]
When more than one image has a 'zoom' class:
```html
<img src="01.png" class="zoom" alt="img"/>
<img src="02.png" class="zoom" alt="img"/>
<img src="03.png" class="zoom" alt="img"/>
```

and we activate the zoom on them:
```javascript
$(function() {
    $('img.zoom').blowup();
});
```

Then the zoom display a zoomed version of the first image, even if we are hover the second or third image.

I tested with latest version of FF and IE.

Best regards,

**Comment by alebarbaja** [comment]
Try with this:

`$('img.zoom').each(function(){
        $(this).blowup();
    })`

**Comment by FGIKCM** [comment]
oO yes, it works like this (in both FF and IE).
Thanks a lot
