### ISSUE TITLE
Shows a plain white image -  not the zoomed in image

### ISSUE THREAD

**Issue by Ben76** [paulkr/blowup.js#8]
Trying to use this plugin in a bootstrap modal. Although the lens appears, it only shows a plain white image. Nothing from the original image.

**Comment by azhidhak** [comment]
only shows a white image for me ?

**Comment by paulkr** [comment]
Seems to be working fine. Check the fiddle below.

[https://jsfiddle.net/xguho1br/3](https://jsfiddle.net/xguho1br/3)
